### ISSUE TITLE
Offline map using osm

### ISSUE THREAD

**Issue by mengoni** [car2go/AnyMaps#10]
Hi,
Is it possible to use offline tiles in assets folder with AnyMaps? It works copying tiles file on SD/osmdroid folder but doesn't If I put them in assets. 
According to osmdroid documentation it should be possible. Maybe the documentation refers to a newer version?
It would be very useful to switch to osm map offline when no internet connection is available.
Thanks

**Comment by Diolor** [comment]
Hi @mengoni ! We have not investigated this functionality yet but sounds interesting. Have you implemented this maybe an only OSMaps app? If it's possible there should be possible in AnyMaps too. We can always bump the dependencies version here if that's required.
