### ISSUE TITLE
Question concerning this project.

### ISSUE THREAD

**Issue by stan2100** [car2go/AnyMaps#11]
Hi,
when I compile the example app, I can only see an open street map (on my smartphone), but no settings menu or car2gos. Is this project intended to provide a working android app to replace the official car2go app to rent car2gos, or do I get something wrong here.  
I have imported this project into android studio.

![screenshot_smartselect_2017-07-05-16-42-23](https://user-images.githubusercontent.com/16188672/27869828-6b672b5c-61a1-11e7-849a-d45409aa99bc.jpg)

**Comment by Diolor** [comment]
Hi @stan2100. I believe you confused slightly some things.

What you see is correct but AnyMaps is a library which is allowing you to use different map providers: Google, OpenMaps, Baidu. 

It is not bound to the car2go API or vehicle loading functionality or any other car2go components.
