### ISSUE TITLE
AddCircle on OSM Map seems not work

### ISSUE THREAD

**Issue by Schoumi** [car2go/AnyMaps#13]
I have a OSM Map and to add Circle i use the code below
```
anyMap.addCircle(new CircleOptions().center(new LatLng(0,0)).radius(1000).fillColor(R.color.colorAccent));
```

But there's no circle in this LatLng position.
I'm doing something wrong or it's a bug?

I've tried the same way the other types of overlay (polygon, polyline,...) and only Marker seems to work.
Any idea why or what can i do to fix this?

**Comment by dmitry-zaitsev** [comment]
`fillColor` takes an `int` representation of the color, not resource id. I added `@ColorInt` annotation for clarity.
