### ISSUE TITLE
Marker on OSM Maps seems at wrong place at low zoom

### ISSUE THREAD

**Issue by Schoumi** [car2go/AnyMaps#14]
When i make a marker, it is at the right position when i zoom in but at a larger zoom, it is 3 or 4 street south of the good place.

Any idea why or if it's bug in your marker implementation or in OSMDroid?

**Comment by dmitry-zaitsev** [comment]
Sorry for the delayed reply.

In the example app we are using custom marker icon, but I forgot to specify the `anchor`. So, it was a bug in the example and not in the library itself.
