### ISSUE TITLE
I got on error upon running the app

### ISSUE THREAD

**Issue by coozgan** [car2go/AnyMaps#6]
Good day, I have tested this project and it doesn't work on me, It gives me this error: (The code is base on the Example + my google API key)

> 05-04 11:39:48.256 10321-10321/? E/AndroidRuntime: FATAL EXCEPTION: main
>                                                    Process: bluenergyfuel.testmap, PID: 10321
>                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{bluenergyfuel.testmap/bluenergyfuel.testmap.MainActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.car2go.maps.google.MapView
>                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
>                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
>                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                        at android.os.Looper.loop(Looper.java:154)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:6176)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
>                                                     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.car2go.maps.google.MapView
>                                                     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.car2go.maps.google.MapView
>                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.car2go.maps.google.MapView" on path: DexPathList[[zip file "/data/app/bluenergyfuel.testmap-1/base.apk"],nativeLibraryDirectories=[/data/app/bluenergyfuel.testmap-1/lib/arm64, /system/lib64, /vendor/lib64]]
>                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
>                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:609)
>                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
>                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
>                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
>                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
>                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
>                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
>                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
>                                                        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
>                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
>                                                        at bluenergyfuel.testmap.MainActivity.onCreate(MainActivity.java:17)
>                                                        at android.app.Activity.performCreate(Activity.java:6679)
>                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
>                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
>                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                        at android.os.Looper.loop(Looper.java:154)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:6176)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by dmitry-zaitsev** [comment]
Hi, first of all thanks for reporting the issue.

- Could you please check if your project has a `:anymaps-google` dependency as well as `:anymaps-base`?
- Perhaps changed the package name and by accident changed package name of `com.car2go.maps.google.MapView`? If you're using example project, you can check that easily by checking the package name of `MapView` class.

**Comment by dmitry-zaitsev** [comment]
Hope that helped to resolve your issue. If not, I will reopen the ticket.
