### ISSUE TITLE
Changing map types

### ISSUE THREAD

**Issue by hardsoft** [car2go/AnyMaps#8]
When I build the example app it appears to be using google maps.

What changes do I need to make to use OSM map. Is there an example of this.

**Comment by dmitry-zaitsev** [comment]
The sample app is updated. Now it uses OSM maps by default.

To switch between map types, you need to do the following:

- Change view type which you're using. There are `MapView` implementations for each map provider. See `activity_main.xml`.
- Change `MapsConfiguration` to match the provider which you are using. For example, use `com.car2go.maps.osm.MapsConfiguration` for OSM and `com.car2go.maps.google.MapsConfiguration` for Google Maps.
- The same way, change `CameraUpdateFactory` and `BitmapDescriptorFactory`.

**Comment by caopeng000** [comment]
能否动态设置使用哪个地图吗？
