### ISSUE TITLE
BitmapDescriptorFactory not initialized

### ISSUE THREAD

**Issue by mengoni** [car2go/AnyMaps#9]
Hi, 
I managed to get visible the OSM map but I can't add markers because method BitmapDescriptorFactory.fromBitmap() doesn't exists in the library and BitmapDescriptorFactory.getInstance().fromBitmap() gives me the following error:
`java.lang.IllegalStateException: Not initialized. Did you forgot to call MapsInitializer?`
even if I call the method in onMapReady callback.

Any help or example would be appreciated. Thanks

**Comment by dmitry-zaitsev** [comment]
There was an outdated exception message (fixed, expect it in a next release). In fact, you need to initialize `MapsConfiguration` for the particular type of the map that you are using. Like that.

```java
MapsConfiguration.getInstance().initialize(this);
```

I also updated the sample app.
